name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: todaysmenu_db
          MYSQL_USER: royroyee
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_ROOT_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
          MYSQL_ROOT_HOST: '%'
        ports:
          - 3306:3306

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Create application-properties.yml
      run: echo "${{ secrets.APPLICATION_PROPERTIES }}" > src/main/resources/application-properties.yml

    - name: Create application-database.yml
      run: echo "${{ secrets.APPLICATION_DATABASE }}" > src/main/resources/database/application-database.yml

    - name: Create application-apikey.yml
      run: echo "${{ secrets.APPLICATION_APIKEY }}" > src/main/resources/api/application-apikey.yml


    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Gradle
      run: ./gradlew build -x test
      env:
          SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/todaysmenu_db?useSSL=false
          SPRING_DATASOURCE_USERNAME: royroyee
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}

  docker-image:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Docker Image
      run: |
        docker build -t royroyee/todays-menu-backend:latest .
        docker push royroyee/todays-menu-backend:latest
